trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Log in to Azure
- task: AzureCLI@2
  inputs:
    azureSubscription: '<Your-Service-Connection-Name>' # Replace with your service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Creating Resource Group..."
      az group create --name myResourceGroup --location eastus
